# Gram-schmidt Algorithm

## Orthonormal expansion

If $ a_1, ... , a_n $ is an orthonormal basis, we have for any n-vector x:

$$
x = (a_1^Tx)a_1 + ... + (a_n^Tx)a_n
$$

## Basic Idea

We will use **Orthonormal expansion** for Gram-schmidt Algorithm.

In the expression

$$ x = (a_1^Tx)a_1 + ... + (a_n^Tx)a_n $$

We will add a new vector $ a_{n+1} $

$$ x = (a_1^Tx)a_1 + ... + (a_n^Tx)a_n + (a_{n+1}^Tx)a_{n+1} $$

If $ a_{n+1} $ is orthonormal to $ a_1 $ ~ $ a_n $ , then that equation holds.

If not, the value of vector $ a_{n+1} $ makes that equation ture is only 0.

## Algorithm

In the equation above, we will change notions a little.

$$
\begin{align}
a_i &= (q_1^Ta_i)q_1 + ... + (q_{i-1}^Ta_i)q_{i-1} + (q_i^Ta_i)q_i\\
&= (q_1^Ta_i)q_1 + ... + (q_{i-1}^Ta_i)q_{i-1} + \tilde q_i\\

\tilde q_i &= a_i - (q_1^Ta_i)q_1 - ... - (q_{i-1}^Ta_i)q_{i-1}

\end{align}
$$
We can consider $ \tilde q_i $ as  the vector without the value of the each direction from $ q_1 $ to $ q_{i-1} $

So, if $ \tilde q_i $ is 0, $ \tilde q_i $ is linearly dependent on $ q_1 $ to $ q_{i-1} $.

## **Finally the algorithm works like this**

> given n-vectors $ a_1, ... , a_k $
>
> for $ i = 1, ... , k $
>
>   1. Orthogonaliztaion:
>
>       $ \tilde q_i = a_i - (q_1^Ta_i)q_1 - ... - (q_{i-1}^Ta_i)q_{i-1} $
>
>   2. Test for linear dependence: if $ \tilde q_i = 0 $, quit
>
>   3. Normalization: $ q_i = \tilde q_i/\| \tilde q_i \| $


## Code

In [4]:
import numpy as np
import numpy.linalg as npl

def gsAlgo(A, tol=1e-10):
    Q = []
    for a in A:
        q_tilde = a
        for q in Q:
            q_tilde -= np.dot(q,a)*q
        if npl.norm(q_tilde) < tol:
            print('Linearly dependent')
            return Q
        Q.append(q_tilde/npl.norm(q_tilde))
    return Q

n = 10
gsAlgo([np.concatenate((np.ones(i),np.zeros(n-i)))for i in range(1, n+1)])

[array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 1., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 1.])]