# QR Factorization

For further use of matrices, we factorize the matrix $A$ to *orthonormal column matrix* $Q$ and *upper trianguler matrix* $R$

## Gram-Schmidt for QR Factorization

To get the orthonormal column matrix $Q$ and upper trainbuler matrix $R$, 

We use Gram-Schmidt Algorithm.

In gram-schmidt algorithm, we could get **orthonormal vector** $ q_1, q_2 ... , q_k $ from **linearly independent vector** $ a_1, a_2, a_3, ... , a_k $.

And for each $ a_i $ we got expression like this.
$$
\begin{align}
a_i &= (q_1^Ta_i)q_1 + ... + (q_{i-1}^Ta_i)q_{i-1} + \|\tilde q_i\|q_i\\

&= R_{1i}q_1 + ... + R_{i-1i}q_{i-1} +R_{ii}q_i
\end{align}
$$

### Gram-Schmidt in matrix notation

And we can convert $ a_i = R_1iq_i  + ... + R_{i-1i}q_{i-1} +R_{ii}q_i $ as matrix notation

$$
\begin{bmatrix} a_1 \\ a_2 \\ ... \\ a_k \end{bmatrix}^T
=
\begin{bmatrix} q_1 \\ q_2 \\ ... \\ q_k \end{bmatrix}^T
\begin{bmatrix} R_{11} & R_{12} & ... & R_{1k} \\
 0 & R_{22} & ... & R_{2k}\\ ... \\ 0 & 0 & ... & R_{kk} \end{bmatrix}
$$

## Python code for qr factorization

In [1]:
import numpy as np
import numpy.linalg as npl

In [6]:
A = np.array([[-3,-4],[4,6],[1,1]])
q,r = npl.qr(A)
print(f'qr of \n{A}\n Q = \n{q} \n R =\n{r}')

qr of 
[[-3 -4]
 [ 4  6]
 [ 1  1]]
 Q = 
[[-0.58834841 -0.45760432]
 [ 0.78446454 -0.52297636]
 [ 0.19611614  0.7190925 ]] 
 R =
[[ 5.09901951  7.256297  ]
 [ 0.         -0.58834841]]


In [12]:
np.matmul(q,r)

array([[-3., -4.],
       [ 4.,  6.],
       [ 1.,  1.]])