# Numpy

In [8]:
import numpy as np

### ndarray의 속성

- **ndim** (차원의 개수)
- **shape**
- size (원소의 개수)
- **dtype** (원소의 자료형)
- itemsize (바이트단위 원소의 크기 int64인 경우 8)
- data (실제 원소를 포함하고 있는 버퍼)
- **strides** (차원별로 다음 요소로 점프하는 데에 필요한 거리를 바이트로 표시)

In [9]:
a = np.array([[[1,2,3],
             [1,2,3],
             [1,2,3],
             [1,2,3]],
             [[1,2,3],
             [1,2,3],
             [1,2,3],
             [1,2,3]]])
a.ndim, a.shape, a.size, a.dtype, a.itemsize, a.data, a.strides

(3, (2, 4, 3), 24, dtype('int64'), 8, <memory at 0x7fb082488e50>, (96, 24, 8))

### Broad casting & Multi dimension array

In [3]:
b = np.array([[10, 20, 30],
              [40, 50, 60]])
c = np.array([1,2,3])
b * c

array([[ 10,  40,  90],
       [ 40, 100, 180]])

In [5]:
np.zeros((2,3)), np.ones((2,3)), np.full((2,3),5), np.eye(3)

(array([[0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 1., 1.],
        [1., 1., 1.]]),
 array([[5, 5, 5],
        [5, 5, 5]]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

### arange, linspace, logspace

In [6]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [7]:
np.linspace(1,10,3)

array([ 1. ,  5.5, 10. ])

In [10]:
np.logspace(1,10,3)

array([1.00000000e+01, 3.16227766e+05, 1.00000000e+10])

### 다차원 배열의 축과 삽입

#### insert

In [14]:
a = np.array([1, 3, 4])
np.insert(a, 1, 2)

array([1, 2, 3, 4])

In [17]:
b = np.array([[1, 1], [2, 2], [3, 3]])
np.insert(b, 1, 4, axis=0), np.insert(b, 1, 4, axis=1)

(array([[1, 1],
        [4, 4],
        [2, 2],
        [3, 3]]),
 array([[1, 4, 1],
        [2, 4, 2],
        [3, 4, 3]]))

#### flip

In [18]:
c = np.array([[1,2,3], [4,5,6]])
np.flip(c, axis=0), np.flip(c, axis=1)

(array([[4, 5, 6],
        [1, 2, 3]]),
 array([[3, 2, 1],
        [6, 5, 4]]))

### 기타 메소드

#### astype

In [19]:
a = np.array([10, 20, 30])
a.astype(np.float64)

array([10., 20., 30.])

#### flatten & transpose & reshape

In [27]:
a = np.array([[1,1], [2,2], [3,3]])
a.flatten(), a.T

(array([1, 1, 2, 2, 3, 3]),
 array([[1, 2, 3],
        [1, 2, 3]]))

In [28]:
a = np.arange(12)
a.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

#### sort

In [24]:
a = np.array([[35, 24, 55], [69, 19, 9], [4, 1, 11]])
a.sort() # default axis = 1
a

array([[24, 35, 55],
       [ 9, 19, 69],
       [ 1,  4, 11]])

In [25]:
a = np.array([[35, 24, 55], [69, 19, 9], [4, 1, 11]])
a.sort(axis=0)
a

array([[ 4,  1,  9],
       [35, 19, 11],
       [69, 24, 55]])

#### append

In [30]:
a = np.array([1,2,3])
b = np.array([[4,5,6], [7,8,9]])
np.append(a, b) # 1차원에 append하기 때문에 flatten 된다.

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
np.append([a],b, axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### 행렬곱셈

In [29]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[10, 20], [30, 40]])
a * b, np.matmul(a,b), a@b

(array([[ 10,  40],
        [ 90, 160]]),
 array([[ 70, 100],
        [150, 220]]),
 array([[ 70, 100],
        [150, 220]]))

### random

- rand() : **균등분포**의 난수 표본을 추출한다
- randn() : **표준 정규 분포**의 난수 표본을 추출한다
- randint() : 최소값과 최대값을 인자로 받아, 주어진 범위 내의 정수 난수를 생성한다. 이때, 최대값은 포함하지 않는다.
- normal() : 평균과 표준편차를 인자로 받아 **정규 분포**의 난수 표본을 추출한다.
- uniform() : **균등분포**에서 표본을 추출한다.
- shuffle() : 주어진 리스트나 다차원 배열의 순서를 임의로 섞는다.
- premutation() : 주어진 범위의 수를 생성하여 섞거나, 배열을 임의의 순서로 섞는다.

In [36]:
nums = np.random.normal(loc=165, scale=10, size=(3,4)).round(2)
nums

array([[160.44, 171.5 , 173.79, 174.73],
       [142.7 , 141.84, 146.1 , 158.64],
       [174.81, 169.07, 152.72, 184.81]])

### reduction

In [37]:
arr = np.array([[1,2,3,4,5],
                [1,2,3,4,5],
                [1,2,3,4,5],
                [1,2,3,4,5],
                [1,2,3,4,5]])
print(np.sum(arr, axis=0))
print(np.sum(arr, axis=1))
print(np.sum(arr, axis=(0,1)))

[ 5 10 15 20 25]
[15 15 15 15 15]
75


### vstack, hstack, r_, c_, column_stack

In [42]:
a = np.array([1,2,3]).reshape((-1,1))
b = np.array([10,20,30]).reshape((-1,1))
a, b

(array([[1],
        [2],
        [3]]),
 array([[10],
        [20],
        [30]]))

In [43]:
print(np.c_[a,b])
print(np.column_stack([a,b]))
print(np.hstack((a,b)))

[[ 1 10]
 [ 2 20]
 [ 3 30]]
[[ 1 10]
 [ 2 20]
 [ 3 30]]
[[ 1 10]
 [ 2 20]
 [ 3 30]]


![img.png](./img/Untitled.png)